import { DeepPartial } from "@/common/domain/types/DeepPartial";
import { DocumentTypeDto } from "@/common/shared/enums/document-type.enum";
import { EntityStatusDto } from "@/common/shared/enums/entity-status.enum";
import { DeliveryFeeTypeDto } from "../../../../common/shared/enums/delivery-fee-type.enum";
import { YesNoStatusDto } from "../../../../common/shared/enums/yes-no-status.enum";

export interface CreateEstablishmentDto {
  userId?: string;
  segmentId?: string;
  licenseId: number;
  oneSignalId?: string;
  affiliate?: string;
  name?: string;
  description?: string;
  stateLegacy?: string;
  cityLegacy?: string;
  subdomain?: string;
  profileImage?: string;
  coverImage?: string;
  themeColor?: string;
  minimumOrder?: number | string;
  acceptsMoney?: YesNoStatusDto;
  acceptsDebitCard?: YesNoStatusDto;
  debitCardBrands?: string;
  acceptsCreditCard?: YesNoStatusDto;
  creditCardBrands?: string;
  acceptsFoodCard?: YesNoStatusDto;
  foodCardBrands?: string;
  acceptsOtherPayment?: YesNoStatusDto;
  otherPaymentDescription?: string;
  acceptsPix?: YesNoStatusDto;
  zipCode?: string;
  addressNumber?: string;
  neighborhood?: string;
  street?: string;
  complement?: string;
  reference?: string;
  businessHoursText?: string;
  allowPickup?: YesNoStatusDto;
  allowDelivery?: YesNoStatusDto;
  deliveryType?: DeliveryFeeTypeDto;
  deliveryValue?: number | string;
  whatsapp?: string;
  contactEmail?: string;
  instagram?: string;
  facebook?: string;
  youtube?: string;
  analyticsCode?: string;
  pixelCode?: string;
  customHtml?: string;
  responsibleName?: string;
  responsibleBirthDate?: string;
  responsibleDocumentType?: DocumentTypeDto;
  responsibleDocument?: string;
  email?: string;
  status: EntityStatusDto;
  forcedStatus?: string;
  operationStatus?: string;
  marketplaceFeature?: YesNoStatusDto;
  variationFeature?: YesNoStatusDto;
  bannerFeature?: YesNoStatusDto;
  triggerFeature: YesNoStatusDto;
  expirationStatus?: string;
  excluded?: string;
  excludedAt?: Date | string;
  productLimit?: string;
  displayMode?: string;
  pixType?: string;
  pixKey?: string;
  pixBeneficiary?: string;
  deliveryName?: string;
  pickupName?: string;
  tableName?: string;
  deliveryEnabled: YesNoStatusDto;
  pickupEnabled: YesNoStatusDto;
  tableEnabled: YesNoStatusDto;
  otherEnabled: YesNoStatusDto;
  otherName?: string;
  token?: string;
  businessHoursJson?: string;
  accessToken?: string;
  calculateShipping: YesNoStatusDto;
  shippingType?: DeliveryFeeTypeDto;
  shippingCompany?: string;
  shippingPassword?: string;
  establishmentPixData?: string;
  mercadoPagoEnabled: YesNoStatusDto;
  mercadoPagoSandbox: boolean;
  mercadoPagoPublicKey?: string;
  mercadoPagoSecretKey?: string;
  pagSeguroEnabled: YesNoStatusDto;
  pagSeguroSandbox: boolean;
  pagSeguroEmail?: string;
  pagSeguroToken?: string;
  mercadoPagoPixEnabled: YesNoStatusDto;
  mercadoPagoPixToken?: string;
  getnetEnabled: YesNoStatusDto;
  getnetSandbox: boolean;
  getnetClientId?: string;
  getnetClientSecret?: string;
  getnetSellerId?: string;
  validity: number;
  triggerCount: number;
  lastLoginAt?: Date | string;
}

export interface UpdateEstablishmentDto extends DeepPartial<CreateEstablishmentDto> {}

export interface EstablishmentPresenterDto {
  id: string;
  userId?: string;
  segmentId?: string;
  licenseId: number;
  oneSignalId?: string;
  affiliate?: string;
  name?: string;
  description?: string;
  stateLegacy?: string;
  cityLegacy?: string;
  subdomain?: string;
  profileImage?: string;
  coverImage?: string;
  themeColor?: string;
  minimumOrder?: number | string;
  acceptsMoney?: YesNoStatusDto;
  acceptsDebitCard?: YesNoStatusDto;
  debitCardBrands?: string;
  acceptsCreditCard?: YesNoStatusDto;
  creditCardBrands?: string;
  acceptsFoodCard?: YesNoStatusDto;
  foodCardBrands?: string;
  acceptsOtherPayment?: YesNoStatusDto;
  otherPaymentDescription?: string;
  acceptsPix?: YesNoStatusDto;
  zipCode?: string;
  addressNumber?: string;
  neighborhood?: string;
  street?: string;
  complement?: string;
  reference?: string;
  businessHoursText?: string;
  allowPickup?: YesNoStatusDto;
  allowDelivery?: YesNoStatusDto;
  deliveryType?: DeliveryFeeTypeDto;
  deliveryValue?: number | string;
  whatsapp?: string;
  contactEmail?: string;
  instagram?: string;
  facebook?: string;
  youtube?: string;
  analyticsCode?: string;
  pixelCode?: string;
  customHtml?: string;
  responsibleName?: string;
  responsibleBirthDate?: string;
  responsibleDocumentType?: DocumentTypeDto;
  responsibleDocument?: string;
  email?: string;
  status: EntityStatusDto;
  forcedStatus?: string;
  operationStatus?: string;
  marketplaceFeature?: YesNoStatusDto;
  variationFeature?: YesNoStatusDto;
  bannerFeature?: YesNoStatusDto;
  triggerFeature: YesNoStatusDto;
  expirationStatus?: string;
  excluded?: string;
  excludedAt?: Date | string;
  productLimit?: string;
  displayMode?: string;
  pixType?: string;
  pixKey?: string;
  pixBeneficiary?: string;
  deliveryName?: string;
  pickupName?: string;
  tableName?: string;
  deliveryEnabled: YesNoStatusDto;
  pickupEnabled: YesNoStatusDto;
  tableEnabled: YesNoStatusDto;
  otherEnabled: YesNoStatusDto;
  otherName?: string;
  token?: string;
  businessHoursJson?: string;
  accessToken?: string;
  calculateShipping: YesNoStatusDto;
  shippingType?: DeliveryFeeTypeDto;
  shippingCompany?: string;
  shippingPassword?: string;
  establishmentPixData?: string;
  mercadoPagoEnabled: YesNoStatusDto;
  mercadoPagoSandbox: boolean;
  mercadoPagoPublicKey?: string;
  mercadoPagoSecretKey?: string;
  pagSeguroEnabled: YesNoStatusDto;
  pagSeguroSandbox: boolean;
  pagSeguroEmail?: string;
  pagSeguroToken?: string;
  mercadoPagoPixEnabled: YesNoStatusDto;
  mercadoPagoPixToken?: string;
  getnetEnabled: YesNoStatusDto;
  getnetSandbox: boolean;
  getnetClientId?: string;
  getnetClientSecret?: string;
  getnetSellerId?: string;
  validity: number;
  triggerCount: number;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  lastLoginAt?: Date | string;
}

export const createEstablishmentRawExample: CreateEstablishmentDto = {
  userId: "00000000-0000-4000-8000-000000000000",
  segmentId: "00000000-0000-4000-8000-000000000000",
  licenseId: 1,
  oneSignalId: "00000000-0000-4000-8000-000000000000",
  affiliate: "example",
  name: "Exemplo",
  description: "example",
  stateLegacy: "example",
  cityLegacy: "example",
  subdomain: "example",
  profileImage: "https://example.com/file.png",
  coverImage: "https://example.com/file.png",
  themeColor: "example",
  minimumOrder: 10.5,
  acceptsMoney: YesNoStatusDto.YES,
  acceptsDebitCard: YesNoStatusDto.YES,
  debitCardBrands: "example",
  acceptsCreditCard: YesNoStatusDto.YES,
  creditCardBrands: "example",
  acceptsFoodCard: YesNoStatusDto.YES,
  foodCardBrands: "example",
  acceptsOtherPayment: YesNoStatusDto.YES,
  otherPaymentDescription: "example",
  acceptsPix: YesNoStatusDto.YES,
  zipCode: "60000000",
  addressNumber: "example",
  neighborhood: "example",
  street: "example",
  complement: "example",
  reference: "example",
  businessHoursText: "example",
  allowPickup: YesNoStatusDto.YES,
  allowDelivery: YesNoStatusDto.YES,
  deliveryType: DeliveryFeeTypeDto.FIXED,
  deliveryValue: 10.5,
  whatsapp: "85999999999",
  contactEmail: "cliente@example.com",
  instagram: "example",
  facebook: "example",
  youtube: "example",
  analyticsCode: "CODE123",
  pixelCode: "CODE123",
  customHtml: "example",
  responsibleName: "Exemplo",
  responsibleBirthDate: "example",
  responsibleDocumentType: DocumentTypeDto.CPF,
  responsibleDocument: "example",
  email: "cliente@example.com",
  status: EntityStatusDto.ACTIVE,
  forcedStatus: "example",
  operationStatus: "example",
  marketplaceFeature: YesNoStatusDto.YES,
  variationFeature: YesNoStatusDto.YES,
  bannerFeature: YesNoStatusDto.YES,
  triggerFeature: YesNoStatusDto.YES,
  expirationStatus: "example",
  excluded: "example",
  productLimit: "example",
  displayMode: "example",
  pixType: "example",
  pixKey: "secret-value",
  pixBeneficiary: "example",
  deliveryName: "Exemplo",
  pickupName: "Exemplo",
  tableName: "Exemplo",
  deliveryEnabled: YesNoStatusDto.YES,
  pickupEnabled: YesNoStatusDto.YES,
  tableEnabled: YesNoStatusDto.YES,
  otherEnabled: YesNoStatusDto.YES,
  otherName: "Exemplo",
  token: "secret-value",
  businessHoursJson: "example",
  accessToken: "secret-value",
  calculateShipping: YesNoStatusDto.YES,
  shippingType: DeliveryFeeTypeDto.FIXED,
  shippingCompany: "example",
  shippingPassword: "secret-value",
  establishmentPixData: "example",
  mercadoPagoEnabled: YesNoStatusDto.YES,
  mercadoPagoSandbox: true,
  mercadoPagoPublicKey: "secret-value",
  mercadoPagoSecretKey: "secret-value",
  pagSeguroEnabled: YesNoStatusDto.YES,
  pagSeguroSandbox: true,
  pagSeguroEmail: "cliente@example.com",
  pagSeguroToken: "secret-value",
  mercadoPagoPixEnabled: YesNoStatusDto.YES,
  mercadoPagoPixToken: "secret-value",
  getnetEnabled: YesNoStatusDto.YES,
  getnetSandbox: true,
  getnetClientId: "00000000-0000-4000-8000-000000000000",
  getnetClientSecret: "secret-value",
  getnetSellerId: "00000000-0000-4000-8000-000000000000",
  validity: 1,
  triggerCount: 1,
};

export const establishmentPresenterRawExample: EstablishmentPresenterDto = {
  id: "00000000-0000-4000-8000-000000000000",
  userId: "00000000-0000-4000-8000-000000000000",
  segmentId: "00000000-0000-4000-8000-000000000000",
  licenseId: 1,
  oneSignalId: "00000000-0000-4000-8000-000000000000",
  affiliate: "example",
  name: "Exemplo",
  description: "example",
  stateLegacy: "example",
  cityLegacy: "example",
  subdomain: "example",
  profileImage: "https://example.com/file.png",
  coverImage: "https://example.com/file.png",
  themeColor: "example",
  minimumOrder: 10.5,
  acceptsMoney: YesNoStatusDto.YES,
  acceptsDebitCard: YesNoStatusDto.YES,
  debitCardBrands: "example",
  acceptsCreditCard: YesNoStatusDto.YES,
  creditCardBrands: "example",
  acceptsFoodCard: YesNoStatusDto.YES,
  foodCardBrands: "example",
  acceptsOtherPayment: YesNoStatusDto.YES,
  otherPaymentDescription: "example",
  acceptsPix: YesNoStatusDto.YES,
  zipCode: "60000000",
  addressNumber: "example",
  neighborhood: "example",
  street: "example",
  complement: "example",
  reference: "example",
  businessHoursText: "example",
  allowPickup: YesNoStatusDto.YES,
  allowDelivery: YesNoStatusDto.YES,
  deliveryType: DeliveryFeeTypeDto.FIXED,
  deliveryValue: 10.5,
  whatsapp: "85999999999",
  contactEmail: "cliente@example.com",
  instagram: "example",
  facebook: "example",
  youtube: "example",
  analyticsCode: "CODE123",
  pixelCode: "CODE123",
  customHtml: "example",
  responsibleName: "Exemplo",
  responsibleBirthDate: "example",
  responsibleDocumentType: DocumentTypeDto.CPF,
  responsibleDocument: "example",
  email: "cliente@example.com",
  status: EntityStatusDto.ACTIVE,
  forcedStatus: "example",
  operationStatus: "example",
  marketplaceFeature: YesNoStatusDto.YES,
  variationFeature: YesNoStatusDto.YES,
  bannerFeature: YesNoStatusDto.YES,
  triggerFeature: YesNoStatusDto.YES,
  expirationStatus: "example",
  excluded: "example",
  excludedAt: "2026-04-28T12:00:00.000Z",
  productLimit: "example",
  displayMode: "example",
  pixType: "example",
  pixKey: "secret-value",
  pixBeneficiary: "example",
  deliveryName: "Exemplo",
  pickupName: "Exemplo",
  tableName: "Exemplo",
  deliveryEnabled: YesNoStatusDto.YES,
  pickupEnabled: YesNoStatusDto.YES,
  tableEnabled: YesNoStatusDto.YES,
  otherEnabled: YesNoStatusDto.YES,
  otherName: "Exemplo",
  token: "secret-value",
  businessHoursJson: "example",
  accessToken: "secret-value",
  calculateShipping: YesNoStatusDto.YES,
  shippingType: DeliveryFeeTypeDto.FIXED,
  shippingCompany: "example",
  shippingPassword: "secret-value",
  establishmentPixData: "example",
  mercadoPagoEnabled: YesNoStatusDto.YES,
  mercadoPagoSandbox: true,
  mercadoPagoPublicKey: "secret-value",
  mercadoPagoSecretKey: "secret-value",
  pagSeguroEnabled: YesNoStatusDto.YES,
  pagSeguroSandbox: true,
  pagSeguroEmail: "cliente@example.com",
  pagSeguroToken: "secret-value",
  mercadoPagoPixEnabled: YesNoStatusDto.YES,
  mercadoPagoPixToken: "secret-value",
  getnetEnabled: YesNoStatusDto.YES,
  getnetSandbox: true,
  getnetClientId: "00000000-0000-4000-8000-000000000000",
  getnetClientSecret: "secret-value",
  getnetSellerId: "00000000-0000-4000-8000-000000000000",
  validity: 1,
  triggerCount: 1,
  createdAt: "2026-04-28T12:00:00.000Z",
  updatedAt: "2026-04-28T12:00:00.000Z",
  lastLoginAt: "2026-04-28T12:00:00.000Z",
};
